name: Deploy SvelteKit to GitHub Pages

on:
  push:
    branches:
      - master # The branch you are deploying from

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest # Use the latest version of Bun

      - name: Install dependencies
        run: bun install

      - name: Build SvelteKit site
        # The BASE_PATH is necessary for the site to work correctly on GitHub Pages
        # It sets the base path to your repository name
        run: bun run build
        env:
          VITE_BASE_PATH: /${{ github.event.repository.name }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # This is the default output directory for SvelteKit's adapter-static
          path: ./build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an authentic source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
